---
- tempfile:
    state: file
    suffix: template
  register: tempfile

- assemble:
    src: "{{ role_path }}/templates/"
    dest: "{{ tempfile.path }}"

- community.kubernetes.k8s:
    state: "{{ state }}"
    template: "{{ tempfile.path }}"
